<Project>
  <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(NETCoreSdkVersion), '7.0'))">
    <DefineConstants>$(DefineConstants);NET7SDK</DefineConstants>
  </PropertyGroup>
<PropertyGroup
  Condition="!$([System.String]::Copy('$(PackageId)').StartsWith('BrycensRanch.'))">
  <_BasePackageId Condition="'$(PackageId)' != ''">$(PackageId)</_BasePackageId>
  <_BasePackageId Condition="'$(_BasePackageId)' == ''">$(MSBuildProjectName)</_BasePackageId>

  <PackageId
    Condition="!$([System.String]::Copy('$(_BasePackageId)').StartsWith('BrycensRanch.'))">
    BrycensRanch.$(_BasePackageId)
  </PackageId>
</PropertyGroup>
</Project>
